/**
 * Solar data domain model and sample-data generation.
 *
 * This module is the single source of truth for the shape of solar readings
 * and the aggregations the UI consumes. It currently synthesises realistic
 * sample data; to use a real source (inverter cloud API, database, CSV import)
 * replace `getDailyReadings` with a fetch/query that returns `DailyReading[]`.
 */

export interface DailyReading {
  /** ISO date string, e.g. "2026-05-01" */
  date: string;
  /** Energy generated by the array, in kWh */
  generationKwh: number;
  /** Energy consumed on-site, in kWh */
  consumptionKwh: number;
  /** Peak power output during the day, in kW */
  peakKw: number;
  /** Hours of usable sunlight */
  sunHours: number;
}

export interface SystemConfig {
  /** Installed DC capacity in kWp */
  capacityKwp: number;
  /** Friendly site name */
  siteName: string;
  /** kg of CO2 avoided per kWh of solar generation */
  co2PerKwh: number;
  /** Grid electricity price used for savings estimates, in currency/kWh */
  pricePerKwh: number;
}

export const SYSTEM_CONFIG: SystemConfig = {
  capacityKwp: 50,
  siteName: "Kepak Solar Array",
  co2PerKwh: 0.233,
  pricePerKwh: 0.34,
};

/**
 * Deterministic pseudo-random generator so the dashboard renders identical
 * sample data on every request (avoids server/client hydration mismatches).
 */
function seededRandom(seed: number): () => number {
  let state = seed % 2147483647;
  if (state <= 0) state += 2147483646;
  return () => {
    state = (state * 16807) % 2147483647;
    return (state - 1) / 2147483646;
  };
}

/**
 * Seasonal generation multiplier (Northern hemisphere): higher in summer,
 * lower in winter. `month` is 0-indexed.
 */
function seasonalFactor(month: number): number {
  // Peaks around June (month 5), troughs around December (month 11).
  return 0.55 + 0.45 * Math.sin(((month - 2) / 12) * 2 * Math.PI);
}

/**
 * Generate `days` of sample readings ending today (inclusive).
 */
export function getDailyReadings(days = 30): DailyReading[] {
  const rng = seededRandom(days * 7919);
  const readings: DailyReading[] = [];
  const today = new Date();

  for (let i = days - 1; i >= 0; i--) {
    const d = new Date(today);
    d.setDate(today.getDate() - i);

    const season = seasonalFactor(d.getMonth());
    const weather = 0.4 + rng() * 0.6; // cloud cover variability
    const sunHours = +(4 + season * 8 * weather).toFixed(1);

    const generationKwh = +(
      SYSTEM_CONFIG.capacityKwp *
      sunHours *
      0.18 *
      (0.85 + rng() * 0.3)
    ).toFixed(1);

    const consumptionKwh = +(20 + rng() * 25).toFixed(1);
    const peakKw = +(
      Math.min(SYSTEM_CONFIG.capacityKwp, generationKwh / Math.max(sunHours, 1) * 2.2)
    ).toFixed(1);

    readings.push({
      date: d.toISOString().slice(0, 10),
      generationKwh,
      consumptionKwh,
      peakKw,
      sunHours,
    });
  }

  return readings;
}

export interface SummaryStats {
  totalGenerationKwh: number;
  totalConsumptionKwh: number;
  selfSufficiencyPct: number;
  co2AvoidedKg: number;
  estimatedSavings: number;
  bestDay: DailyReading | null;
  avgDailyGenerationKwh: number;
}

export function summarise(readings: DailyReading[]): SummaryStats {
  if (readings.length === 0) {
    return {
      totalGenerationKwh: 0,
      totalConsumptionKwh: 0,
      selfSufficiencyPct: 0,
      co2AvoidedKg: 0,
      estimatedSavings: 0,
      bestDay: null,
      avgDailyGenerationKwh: 0,
    };
  }

  const totalGenerationKwh = readings.reduce((s, r) => s + r.generationKwh, 0);
  const totalConsumptionKwh = readings.reduce((s, r) => s + r.consumptionKwh, 0);
  const bestDay = readings.reduce((best, r) =>
    r.generationKwh > best.generationKwh ? r : best
  );

  // Solar can only offset consumption up to what is actually used.
  const offset = Math.min(totalGenerationKwh, totalConsumptionKwh);

  return {
    totalGenerationKwh: +totalGenerationKwh.toFixed(1),
    totalConsumptionKwh: +totalConsumptionKwh.toFixed(1),
    selfSufficiencyPct: +((offset / totalConsumptionKwh) * 100).toFixed(1),
    co2AvoidedKg: +(totalGenerationKwh * SYSTEM_CONFIG.co2PerKwh).toFixed(1),
    estimatedSavings: +(totalGenerationKwh * SYSTEM_CONFIG.pricePerKwh).toFixed(2),
    bestDay,
    avgDailyGenerationKwh: +(totalGenerationKwh / readings.length).toFixed(1),
  };
}
